/**
 * This file Copyright (c) 2003-2009 Magnolia International
 * Ltd.  (http://www.magnolia.info). All rights reserved.
 *
 *
 * This file is dual-licensed under both the Magnolia
 * Network Agreement and the GNU General Public License.
 * You may elect to use one or the other of these licenses.
 *
 * This file is distributed in the hope that it will be
 * useful, but AS-IS and WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE, TITLE, or NONINFRINGEMENT.
 * Redistribution, except as permitted by whichever of the GPL
 * or MNA you select, is prohibited.
 *
 * 1. For the GPL license (GPL), you can redistribute and/or
 * modify this file under the terms of the GNU General
 * Public License, Version 3, as published by the Free Software
 * Foundation.  You should have received a copy of the GNU
 * General Public License, Version 3 along with this program;
 * if not, write to the Free Software Foundation, Inc., 51
 * Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * 2. For the Magnolia Network Agreement (MNA), this file
 * and the accompanying materials are made available under the
 * terms of the MNA which accompanies this distribution, and
 * is available at http://www.magnolia.info/mna.html
 *
 * Any modifications to this file must keep this entire header
 * intact.
 *
 */
package info.magnolia.cms.cache;

import info.magnolia.cms.security.Digester;
import info.magnolia.context.MgnlContext;

import java.util.Collection;

import javax.servlet.http.HttpServletRequest;

import org.apache.commons.lang.ArrayUtils;


/**
 * @author Sameer Charles $Id$
 */
public class RoleBasedCacheFilter extends CacheFilter {

    /**
     * This will: - Consolidate all roles sorted by node name - Generate MD5 of this consolidated string - Adds this MD5
     * to the key generated by cache manager
     */
    public String getCacheKey(HttpServletRequest request) {
        String key = MgnlContext.getAggregationState().getCurrentURI();
        return this.generateMD5Key(MgnlContext.getUser().getAllRoles(), key);
    }

    /**
     * generate an MD5 of all roles assigned to this user
     * @param assignedRoles
     * @param key as created by configured CacheManager
     */
    private String generateMD5Key(Collection assignedRoles, String key) {
        String asString = ArrayUtils.toString(assignedRoles);
        StringBuffer buffer = new StringBuffer(key).append(".").append(Digester.getMD5Hex(asString));
        return buffer.toString();
    }

}
