/**
 *
 * Magnolia and its source-code is licensed under the LGPL.
 * You may copy, adapt, and redistribute this file for commercial or non-commercial use.
 * When copying, adapting, or redistributing this document in keeping with the guidelines above,
 * you are required to provide proper attribution to obinary.
 * If you reproduce or distribute the document without making any substantive modifications to its content,
 * please use the following attribution line:
 *
 * Copyright 1993-2005 obinary Ltd. (http://www.obinary.com) All rights reserved.
 *
 */
package info.magnolia.module.admininterface;

import info.magnolia.cms.gui.control.Tree;

import javax.servlet.http.HttpServletRequest;


/**
 * Admin interface tree handler. Each repository in the main admin interface is handled in a separate class which
 * implements AdminTree.
 * @author Fabrizio Giustina
 * @version $Id$
 */
public interface AdminTree {

    /**
     * @param tree Tree generated by the AdminInterfaceServlet. The content must be set here.
     * @param request current HttpServletRequest
     * @param path path parameter in request
     * @param pathOpen pathOpen parameter in request
     * @param pathSelected pathSelected parameter in request
     * @param create create a new item?
     * @param createItemType type for the new item
     */
    void configureTree(Tree tree, HttpServletRequest request, String path, String pathOpen, String pathSelected,
        boolean create, String createItemType);
}
