package info.magnolia.module.adminInterface;

import info.magnolia.cms.gui.control.Tree;

import javax.servlet.http.HttpServletRequest;


/**
 * Admin interface tree handler. Each repository in the main admin interface is handled in a separate class which
 * implements AdminTree.
 * @author Fabrizio Giustina
 * @version $Id: $
 */
public interface AdminTree {

    /**
     * @param tree Tree generated by the AdminInterfaceServlet. The content must be set here.
     * @param request current HttpServletRequest
     * @param path path parameter in request
     * @param pathOpen pathOpen parameter in request
     * @param pathSelected pathSelected parameter in request
     * @param create create a new item?
     * @param createItemType type for the new item
     */
    void configureTree(Tree tree, HttpServletRequest request, String path, String pathOpen, String pathSelected,
        boolean create, String createItemType);
}
